apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloud-project-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloud-project

  template:
    metadata:
      labels:
        app: cloud-project

    spec:
      containers:
      - name: cloud-project-container
        image: 12308425/cloud_project
        ports:
        - containerPort: 80