apiVersion: v1
kind: Service

metadata:
  name: cloud-project-service

spec:
  type: NodePort

  selector:
    app: cloud-project

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007